# Generated by Django 5.1.15 on 2026-04-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoardMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                (
                    "position",
                    models.CharField(
                        help_text="e.g. 'President', 'First Vice President', 'Director at Large'", max_length=200
                    ),
                ),
                ("photo", models.ImageField(blank=True, upload_to="board/photos/")),
                ("term_year", models.CharField(help_text="e.g. '2025-2026'", max_length=20)),
                ("is_current", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
    ]
