# Generated by Django 5.1.15 on 2026-04-10 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ActivityGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, help_text="Rich-text description (HTML)")),
                (
                    "schedule",
                    models.CharField(blank=True, help_text="e.g. 'Wednesdays 1:00 p.m. - 3:00 p.m.'", max_length=300),
                ),
                (
                    "location",
                    models.CharField(blank=True, help_text="Room or area within Dogwood Pavilion", max_length=200),
                ),
                ("leader_name", models.CharField(blank=True, max_length=200)),
                ("leader_phone", models.CharField(blank=True, max_length=30)),
                ("leader_email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="groups", to="activities.category"
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
    ]
