# Generated by Django 5.1.15 on 2026-04-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SupportResource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("org_name", models.CharField(max_length=300, verbose_name="Organization name")),
                ("description", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("website", models.URLField(blank=True)),
                (
                    "schedule",
                    models.CharField(blank=True, help_text="e.g. '24 Hours a Day — 7 Days a Week'", max_length=300),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["org_name"],
            },
        ),
    ]
